### ISSUE TITLE
READMEをかく

### ISSUE THREAD

**Issue by takuma-shiraki** [op-tennis/Practice-Backend#7]
## 開発環境の作成方法を記載する

**Comment by takuma-shiraki** [comment]
Dockerでコンテナ立てる方法がわからん下記の方法で合ってる？

```sh
colima start
docker-compose up -d
```

コンテナで`npm run dev`を実行して、コンソールに下記の表記が出る

```
> app@1.0.0 dev
> npx ts-node-dev --respawn src/app.ts

[INFO] 21:32:15 ts-node-dev ver. 2.0.0 (using ts-node ver. 10.9.2, typescript ver. 5.4.5)
Hello, world!
1
2
3
```

**Comment by takuma-shiraki** [comment]
サーバーアクセスできてないみたい
```sh
docker ps
CONTAINER ID   IMAGE                             COMMAND                   CREATED          STATUS          PORTS                                       NAMES
b0c7e21fbfc2   practice-backend-backend-server   "docker-entrypoint.s…"   11 minutes ago   Up 11 minutes   0.0.0.0:8080->8080/tcp, :::8080->8080/tcp   practice-backend-backend-server-1

curl http://localhost:8080
curl: (52) Empty reply from server
```

**Comment by takuma-shiraki** [comment]
dockerを起動すると下記のエラーが出る

```sh
docker run --name practice-backend-server -p 8081:80 practice-backend-backend-server


> app@1.0.0 dev
> npx ts-node-dev --respawn src/app.ts

/app/node_modules/resolve/lib/sync.js:113
    throw err;
    ^

Error: Cannot find module 'src/app.ts' from '/app'
    at Function.resolveSync [as sync] (/app/node_modules/resolve/lib/sync.js:111:15)
    at resolveRequest (/app/node_modules/ts-node-dev/lib/resolveMain.js:18:24)
    at exports.resolveMain (/app/node_modules/ts-node-dev/lib/resolveMain.js:30:20)
    at exports.runDev (/app/node_modules/ts-node-dev/lib/index.js:53:30)
    at Object.<anonymous> (/app/node_modules/ts-node-dev/lib/bin.js:136:4)
    at Module._compile (node:internal/modules/cjs/loader:1368:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1426:10)
    at Module.load (node:internal/modules/cjs/loader:1205:32)
    at Module._load (node:internal/modules/cjs/loader:1021:12)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:142:12) {
  code: 'MODULE_NOT_FOUND'
}

Node.js v21.7.3
```

**Comment by takuma-shiraki** [comment]
## 名前を変えるには

```sh
docker-compose -p backend-server up

docker ps
CONTAINER ID   IMAGE                           COMMAND                   CREATED          STATUS          PORTS                                       NAMES
e7ccf82bbed1   backend-server-backend-server   "docker-entrypoint.s…"   13 seconds ago   Up 12 seconds   0.0.0.0:8080->8080/tcp, :::8080->8080/tcp   backend-server-backend-server-1
```

IMAGEの名前`backend-server-backend-server`はこのような命名ルールらしい
[コマンドの名前]-[docker-compose.ymlの名前]

```yml
version: "3.3"

services:
  # ↓docker-compose.ymlの名前
  backend-server:
    build:
      context: .
      dockerfile: ./Dockerfile
    tty: true
    ports:
      - 8080:8080
    volumes:
      - ./:/app
```

**Comment by takuma-shiraki** [comment]
docker-compose.ymlのportを80にするとServerにアクセスできない

```yml
    ports:
      - 8080:8080
```

```yml
    ports:
      - 8080:8080
```

下記のルールで決まっている
- `http://localhost:<Host Port>`
- <Container Port>はDockerfileで使っているimageによるらしい
  - https://qiita.com/nakad119/questions/1064692664cec017ef30

```yml
    ports:
      - "<Host Port>:<Container Port>"
```
